name: "CI"

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build
        run: nix develop -c "make"

      - name: Check formatting
        run: |
          nix develop -c clang-format -i $(find . -name '*.cpp' -o -name '*.hpp')
          git diff --exit-code || (echo "Code is not properly formatted!"; exit 1)

      # - name: Run static analysis
      #   run: |
      #     nix develop -c cppcheck --error-exitcode=100 .

      # - name: Run valgrind
      #   run: |
      #     nix develop -c valgrind --error-exitcode=100 --leak-check=full ./result/bin/terminder
