name: "CI"

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build
        run: nix develop -c "make"

      - name: Check formatting
        run: nix develop -c bash -c "make format && git diff --exit-code"

      - name: Clang tidy
        run: nix develop -c make tidy-ci

      - name: cppcheck
        run: nix develop -c make check
